### ISSUE TITLE
Could you improve the project description. Missing hardware requirements 

### ISSUE THREAD

**Issue by stuart1975** [DenTechs/Virtual_Desktop_Body_Tracking_Configurator#4]
Could you improve the project description?
It is not clear what are the hardware requirements for this software e.g. which headset or trackers are required for e.g. Meta Quest 3.
There are so many options clickable. I have no clue what options are supported by the headset and which require for e.g. a vive tracker.

Also an example configuration for VR Game Blade & Sorcery would help how to use it.

**Comment by DenTechs** [comment]
All emulated trackers available for quest 1 / 2 / pro / 3. This software is
an accompaniment to Virtual Desktop so having the requirements here would
be redundant.

Furthermore, there are tooltips for every option if you hover over them,
explaining what they do and if they’re recommended or not.

And regarding blade and sorcery, emulated trackers are not recommended for
that game because the legs are only estimated and do not support kicking or
etc, making them useless for the game.
